//+======================================================================
// $Source: /disk/cvs//TANGO/DeviceServer/JClock/getTimeDateCmd.java,v $
//
// Project:      Tango Device Server
//
// Description:  Java source code for the command TemplateClass of the
//               DSClock class.
//
// $Author: raph $
//
// $Revision: 1.1.1.1 $
//
// $Log: getTimeDateCmd.java,v $
// Revision 1.1.1.1  2001/04/17 11:21:05  raph
// initial work
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-======================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//             (c) - Pascal Verdier - ESRF
//=============================================================================



/**
 * @author	$Author: raph $
 * @version	$Revision: 1.1.1.1 $
 */



import org.omg.CORBA.*;
import Tango.*;
import TangoDs.*;

/**
 *	Class Description:
 *	return date and time of server
 */


public class getTimeDateCmd extends Command implements TangoConst
{
	//===============================================================
	/**
	 *	Constructor for Command class getTimeDateCmd
	 *
	 *	@param	name	command name
	 *	@param	in	argin type
	 *	@param	out	argout type
	 */
	//===============================================================
	public getTimeDateCmd(String name,int in,int out)
	{
		super(name, in, out);
	}

	//===============================================================
	/**
	 *	Constructor for Command class getTimeDateCmd
	 *
	 *	@param	name            command name
	 *	@param	in              argin type
	 *	@param	in_comments     argin description
	 *	@param	out             argout type
	 *	@param	out_comments    argout description
	 */
	//===============================================================
	public getTimeDateCmd(String name,int in,int out, String in_comments, String out_comments)
	{
		super(name, in, out, in_comments, out_comments);
	}
	//===============================================================
	/**
	 *	return the result of the device's command.
	 */
	//===============================================================
	public Any execute(DeviceImpl device,Any in_any) throws DevFailed
	{
		TangoUtil.out2.println("getTimeDateCmd.execute(): arrived");

		return insert(((DSClock)(device)).get_time_date());
	}

	//===============================================================
	/**
	 *	Check if it is allowed to execute the command.
	 */
	//===============================================================
	public boolean is_allowed(DeviceImpl device, Any data_in)
	{
		if (device.get_state() == DevState.OFF)
		{
			//	End of Generated Code

			//	Re-Start of Generated Code
			return false;
		}
		return true;
	}

}
