[Common]
Disassembler Left=2400
Disassembler Top=5775
Disassembler Width=6615
Disassembler Height=2745
watch watch:DisplayOptions=3 Value Address Module Type
watch watch:Sort=(No Sort)
watch watch:Symbol 1=ADR Expand 3
watch watch:Number Of Symbols=2
watch watch:Display=OLD 556 10 769 559 1
dump dump:Hot=Yes
dump dump:Space=Program
dump dump:Group by=Bytes
dump dump:PrettyAddresses=No
dump dump:Banks (part 1)=0x00
dump dump:Base Address=0
dump dump:Page=0
dump dump:Base=Hexadecimal
dump dump:Display=OLD 338 138 769 559 1
modulegradator.txt Left=1140
modulegradator.txt Top=1200
modulegradator.txt Width=5490
modulegradator.txt Height=3135
modulegradator.txt Line=39
Forms=modulegradator.txt
Modules=watch watch;dump dump
Breaks=
dump dump:Addresses (part 1)=0x80000000
watch watch:Symbol 2=ARCP Expand 3
