// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

//
// IDL:pcitor48:1.0
//
/***/

public interface pcitor48Operations
{
    //
    // IDL:pcitor48/SetLed:1.0
    //
    /***/

    void
    SetLed(short number);

    //
    // IDL:pcitor48/Read:1.0
    //
    /***/

    boolean
    Read(short number);
}
