// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

//
// IDL:pcitor48:1.0
//
/***/

public class pcitor48_impl extends pcitor48POA
{
    private org.omg.PortableServer.POA poa_;

    public
    pcitor48_impl(org.omg.PortableServer.POA poa)
    {
        poa_ = poa;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(poa_ != null)
            return poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:pcitor48/SetLed:1.0
    //
    public void
    SetLed(short number)
    {
        // TODO: implement
	System.out.println("SetLed "+ number);
    }

    //
    // IDL:pcitor48/Read:1.0
    //
    public boolean
    Read(short number)
    {
        // TODO: implement
	System.out.println("Read "+ number);
        boolean _r = ((number % 2) == 0);
        return _r;
    }
}
