// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

//
// IDL:pcitor48:1.0
//
/***/

public interface pcitor48 extends pcitor48Operations,
                                  org.omg.CORBA.Object,
                                  org.omg.CORBA.portable.IDLEntity
{
}
