// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package essai;

//
// IDL:Sample1:1.0
//
/***/

public interface Sample1Operations
{
    //
    // IDL:Sample1/function1:1.0
    //
    /***/

    void
    function1();
}
