// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package essai;

//
// IDL:Sample1:1.0
//
/***/

public interface Sample1 extends Sample1Operations,
                                 org.omg.CORBA.Object,
                                 org.omg.CORBA.portable.IDLEntity
{
}
