/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PCITOR48_H_RPCGEN
#define _PCITOR48_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PCITOR 7654321
#define VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SetLed 1
extern  char ** setled_1(int *, CLIENT *);
extern  char ** setled_1_svc(int *, struct svc_req *);
#define ClrLed 1
extern  char ** clrled_1(int *, CLIENT *);
extern  char ** clrled_1_svc(int *, struct svc_req *);
extern int pcitor_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SetLed 1
extern  char ** setled_1();
extern  char ** setled_1_svc();
#define ClrLed 1
extern  char ** clrled_1();
extern  char ** clrled_1_svc();
extern int pcitor_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PCITOR48_H_RPCGEN */
