static const char *RcsId = "$Header: /opt2/cvs//TANGO/DeviceServer/Horloge/HorlogeClass.cpp,v 1.1.1.1 2002/05/15 10:05:03 raph Exp $";
//+=============================================================================
//
// file :        HorlogeClass.cpp
//
// description : C++ source for the HorlogeClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the Horloge once per process.
//
// project :     TANGO Device Server
//
// $Author: raph $
//
// $Revision: 1.1.1.1 $
//
// $Log: HorlogeClass.cpp,v $
// Revision 1.1.1.1  2002/05/15 10:05:03  raph
// initial cvs import
//
//
// copyleft :   European Synchrotron Radiation Facility
//              BP 220, Grenoble 38043
//              FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================


#include <tango.h>

#include <Horloge.h>
#include <HorlogeClass.h>


namespace Horloge
{
//+----------------------------------------------------------------------------
//
// method : 		DevTestCmdCmd::DevTestCmdCmd()
// 
// description : 	constructor for the command of the Horloge.
//
// In : - name : The command name
//		- in : The input parameter type
//		- out : The output parameter type
//		- in_desc : The input parameter description
//		- out_desc : The output parameter description
//
//-----------------------------------------------------------------------------
DevTestCmdCmd::DevTestCmdCmd(	const char		*name,
								Tango::CmdArgType in,
				       			Tango::CmdArgType out,
								const char		*in_desc,
				       			const char		*out_desc )
:Command(name,in,out,in_desc,out_desc)
{
}
//
//	Constructor without in/out parameters description
//
DevTestCmdCmd::DevTestCmdCmd(	const char		*name,
								Tango::CmdArgType in,
				       			Tango::CmdArgType out)
:Command(name,in,out)
{
}




//+----------------------------------------------------------------------------
//
// method : 		DevTestCmdCmd::is_allowed()
// 
// description : 	method to test whether command is allowed or not in this
//			state. In this case, the command is allowed only if
//			the device is in ON state
//
// in : - device : The device on which the command must be excuted
//		- in_any : The command input data
//
// returns :	boolean - true == is allowed , false == not allowed
//
//-----------------------------------------------------------------------------
bool DevTestCmdCmd::is_allowed(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return true;
}




//+----------------------------------------------------------------------------
//
// method : 		DevTestCmdCmd::execute()
// 
// description : 	method to trigger the execution of the command.
//                PLEASE DO NOT MODIFY this method core without pogo   
//
// in : - device : The device on which the command must be excuted
//		- in_any : The command input data
//
// returns : The command output data (packed in the Any object)
//
//-----------------------------------------------------------------------------
CORBA::Any *DevTestCmdCmd::execute(Tango::DeviceImpl *device,const CORBA::Any &in_any)
{

	cout2 << "DevTestCmdCmd::execute(): arrived" << endl;

	Tango::DevLong	argin;
	extract(in_any, argin);

	return insert((static_cast<Horloge *>(device))->dev_test_cmd(argin));
}



//+----------------------------------------------------------------------------
//
// method : 		DevGetDateCmd::DevGetDateCmd()
// 
// description : 	constructor for the command of the Horloge.
//
// In : - name : The command name
//		- in : The input parameter type
//		- out : The output parameter type
//		- in_desc : The input parameter description
//		- out_desc : The output parameter description
//
//-----------------------------------------------------------------------------
DevGetDateCmd::DevGetDateCmd(	const char		*name,
								Tango::CmdArgType in,
				       			Tango::CmdArgType out,
								const char		*in_desc,
				       			const char		*out_desc )
:Command(name,in,out,in_desc,out_desc)
{
}
//
//	Constructor without in/out parameters description
//
DevGetDateCmd::DevGetDateCmd(	const char		*name,
								Tango::CmdArgType in,
				       			Tango::CmdArgType out)
:Command(name,in,out)
{
}




//+----------------------------------------------------------------------------
//
// method : 		DevGetDateCmd::is_allowed()
// 
// description : 	method to test whether command is allowed or not in this
//			state. In this case, the command is allowed only if
//			the device is in ON state
//
// in : - device : The device on which the command must be excuted
//		- in_any : The command input data
//
// returns :	boolean - true == is allowed , false == not allowed
//
//-----------------------------------------------------------------------------
bool DevGetDateCmd::is_allowed(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return true;
}




//+----------------------------------------------------------------------------
//
// method : 		DevGetDateCmd::execute()
// 
// description : 	method to trigger the execution of the command.
//                PLEASE DO NOT MODIFY this method core without pogo   
//
// in : - device : The device on which the command must be excuted
//		- in_any : The command input data
//
// returns : The command output data (packed in the Any object)
//
//-----------------------------------------------------------------------------
CORBA::Any *DevGetDateCmd::execute(Tango::DeviceImpl *device,const CORBA::Any &in_any)
{

	cout2 << "DevTemplateCmd::execute(): arrived" << endl;

	return insert((static_cast<Horloge *>(device))->dev_get_date());
}


//
//----------------------------------------------------------------
//	Initialize pointer for singleton pattern
//----------------------------------------------------------------
//
HorlogeClass *HorlogeClass::_instance = NULL;

//+----------------------------------------------------------------------------
//
// method : 		HorlogeClass::HorlogeClass(string &s)
// 
// description : 	constructor for the HorlogeClass
//
// in : - s : The class name
//
//-----------------------------------------------------------------------------
HorlogeClass::HorlogeClass(string &s):DeviceClass(s)
{

	cout2 << "Entering HorlogeClass constructor" << endl;
	
	cout2 << "Leaving HorlogeClass constructor" << endl;

}
//+----------------------------------------------------------------------------
//
// method : 		HorlogeClass::~HorlogeClass()
// 
// description : 	destructor for the HorlogeClass
//
//-----------------------------------------------------------------------------
HorlogeClass::~HorlogeClass()
{
	_instance = NULL;
}

//+----------------------------------------------------------------------------
//
// method : 		HorlogeClass::instance
// 
// description : 	Create the object if not already done. Otherwise, just
//			return a pointer to the object
//
// in : - name : The class name
//
//-----------------------------------------------------------------------------
HorlogeClass *HorlogeClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new HorlogeClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

HorlogeClass *HorlogeClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}

//+----------------------------------------------------------------------------
//
// method : 		HorlogeClass::command_factory
// 
// description : 	Create the command object(s) and store them in the 
//			command list
//
//-----------------------------------------------------------------------------
void HorlogeClass::command_factory()
{
	command_list.push_back(new DevGetDateCmd("DevGetDate",
		Tango::DEV_VOID, Tango::DEV_STRING,
		"",
		""));
	command_list.push_back(new DevTestCmdCmd("DevTestCmd",
		Tango::DEV_LONG, Tango::DEV_STRING,
		"an integer to parse",
		"parsed int"));
}

//+----------------------------------------------------------------------------
//
// method : 		HorlogeClass::device_factory
// 
// description : 	Create the device object(s) and store them in the 
//			device list
//
// in :		Tango::DevVarStringArray *devlist_ptr : The device name list
//
//-----------------------------------------------------------------------------
void HorlogeClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	
	for (long i=0 ; i < devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i] << endl;
						
		// Create device and add it into the device list
		//----------------------------------------------------
		device_list.push_back(new Horloge(this, (*devlist_ptr)[i]));							 

		// Export device to the outside world
		// Check before id database used.
		//---------------------------------------------
		if (Tango::Util::_UseDb == true)
			export_device(device_list.back());
		else
			export_device(device_list.back(), (*devlist_ptr)[i]);
	}
}

}	// namespace
