/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CAN_H_RPCGEN
#define _CAN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CAN 1234567
#define LGM 1

#if defined(__STDC__) || defined(__cplusplus)
#define lireCAN 1
extern  float * lirecan_1(int *, CLIENT *);
extern  float * lirecan_1_svc(int *, struct svc_req *);
extern int can_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define lireCAN 1
extern  float * lirecan_1();
extern  float * lirecan_1_svc();
extern int can_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CAN_H_RPCGEN */
