/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "can.h"

float * 
lirecan_1_svc(int *argp, struct svc_req *rqstp)
{
	static float  result;
	struct sockaddr_in *adr;
	int ipad;
	
	/*
	 * insert server code here
	 */
	printf("accès à la voie n° %d\n",*argp);
	adr=svc_getcaller(rqstp->rq_xprt);
	ipad=ntohl(adr->sin_addr.s_addr);
	
	printf("par %d.%d.%d.%d\n",	(ipad >> 24) & 0xFF, 
					(ipad >> 16) & 0xFF,
					(ipad >> 8)  & 0xFF,
					(ipad )      & 0xFF);
	
	result=3.1415927;
	
	return &result;
}
