/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "can.h"


void 
can_1(char *host, int lirecan_1_arg)
{
	CLIENT *clnt;
	float  *result_1;
	

#ifndef	DEBUG
	clnt = clnt_create (host, CAN, LGM, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = lirecan_1(&lirecan_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	//afficher la valeur reçue
	printf("read on DAC %f\n",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int channel;
	
	if (argc < 2) {
		printf ("usage: %s server_host channel_number\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sscanf(argv[2],"%d",&channel);
	
	can_1 (host,channel);
exit (0);
}
