/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mplayer.h"

bool_t
xdr_FileName (XDR *xdrs, FileName *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXFILENAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_File (XDR *xdrs, File *objp)
{
	register int32_t *buf;

	 if (!xdr_FileName (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, 1000000L))
	 	 return FALSE;
	 /*if (!xdr_opaque (xdrs, (char **)&objp->data.data_val, (u_int) objp->data.data_len))
		 return FALSE;*/
	return TRUE;
}
