/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mplayer.h"

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

void
mplayer_1(char *host, char *fname)
{
	CLIENT *clnt;
	void  *result_1;
	File  mplay_1_arg;
	int 	fd, //file descriptor
		n;  //compteur
	struct stat stat_buf;

	/*lecture du fichier dans buffer*/
	fd=open(fname,O_RDONLY);
	if (fd<0) exit(0);
	n=0;
	mplay_1_arg.name=fname;
	mplay_1_arg.data.data_len=0;
	fstat(fd,&stat_buf);
	mplay_1_arg.data.data_val=malloc(stat_buf.st_size);
	do {
		n=read(fd,mplay_1_arg.data.data_val + mplay_1_arg.data.data_len,stat_buf.st_size);
		if (n>0) mplay_1_arg.data.data_len += n;
	}
	while(n>0);
	close(fd);
	printf("fichier %s %d 0x%x %d\n",fname,stat_buf.st_size,
		mplay_1_arg.data.data_val,mplay_1_arg.data.data_len);
	
	/*transfert du buffer*/
#ifndef	DEBUG
	//tcp for huge data transfer
	clnt = clnt_create (host, mplayer, LGM, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = mplay_1(&mplay_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	if (argc < 3) {
		printf ("usage: %s server_host filename\n", argv[0]);
		exit (1);
	}
	mplayer_1 (argv[1],argv[2]);
exit (0);
}
