/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mplayer.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#define LEN 1000


char XMMS[100]="xmms ";
void *
mplay_1_svc(File *argp, struct svc_req *rqstp)
{
	static char * result;
	int 	fd, //file descriptor
		n,w;  //compteur
	char buffer[LEN];

	/*
	 * insert server code here
	 */
	printf("fichier reçu %s\n",argp->name);


	/*lecture du fichier dans buffer*/
	fd=open(argp->name,O_CREAT|O_WRONLY|O_APPEND,S_IRWXU);
	n=0;
	while (n<argp->data.data_len) {
		w=write(fd,argp->data.data_val+n, argp->data.data_len-n);
		n +=w;
		}	
	close(fd);
	
	strcat(XMMS,argp->name);
	system (XMMS);
	return (void *) &result;
}
