/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MPLAYER_H_RPCGEN
#define _MPLAYER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXFILENAMELEN 255

typedef char *FileName;

struct File {
	FileName name;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct File File;

#define mplayer 1234567
#define LGM 1

#if defined(__STDC__) || defined(__cplusplus)
#define mplay 1
extern  void * mplay_1(File *, CLIENT *);
extern  void * mplay_1_svc(File *, struct svc_req *);
extern int mplayer_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mplay 1
extern  void * mplay_1();
extern  void * mplay_1_svc();
extern int mplayer_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_FileName (XDR *, FileName*);
extern  bool_t xdr_File (XDR *, File*);

#else /* K&R C */
extern bool_t xdr_FileName ();
extern bool_t xdr_File ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MPLAYER_H_RPCGEN */
