/*
 * RP Tue Apr 13 18:56:17 CEST 1999
 *
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 
 bash-2.01$ rpcinfo -p localhost
   program vers proto   port
    100000    2   tcp    111  portmapper
    100000    2   udp    111  portmapper
   1234567    1   udp   1024
   1234567    1   tcp   1083

 */

#include "essai.h"

char ** 
test_1_svc(char **argp, struct svc_req *rqstp)
{

	static char * result="OK";

	/*
	 * insert server code here
	 */
	printf("serv arg =%s\n",*argp);
	printf("ser res =%s\n",result);

	return(&result);
}
