/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ESSAI_H_RPCGEN
#define _ESSAI_H_RPCGEN

#include <rpc/rpc.h>


#define TEST ((u_long)1234567)
#define VERS ((u_long)1)


extern  char ** test_1(char **, CLIENT *);
extern  char ** test_1_svc(char **, struct svc_req *);



#endif /* !_ESSAI_H_RPCGEN */
