/*
 * RP Tue Apr 13 18:56:17 CEST 1999
 *
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "essai.h"


void
test( char* host )
{
	CLIENT *clnt;
	char * *result_1;
	char * test_1_arg="hello!!!";
	
	//clnt = clnt_create(host, TEST, VERS, "udp");
	clnt = clnt_create(host, TEST, VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	printf("arg =%s\n",test_1_arg);
	result_1 = test_1(&test_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("res =%s\n",*result_1);
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	test( host );
}
